spring:
  config:
    activate:
      on-profile: dev
  application:
    name: backend-kltn
  
  datasource:
    url: ${SPRING_MYSQL_DATASOURCE_URL:jdbc:mysql://localhost:3306/kltn-dev?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update # hoặc 'create-drop' nếu muốn tạo mới mỗi lần khởi động
    show-sql: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
jwt:
  secret: k8wT5KF1ZrFojvpXJbhXOcYVv44lCKvOwQudCRY6HjxxTGH3WQbQDHEFZjhS+mCE
  header: Authorization
  prefix: Bearer
  expirationMs: 86400000 # 1 ngày tính bằng milliseconds